networks:
  api:

volumes:
  buckets:
  database:

services:
  api:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - database:/data
    networks:
      - api
    env_file: .env
    environment:
      - DOMAIN=http://localhost:5173
      - SIGNUPS_VERIFY=true
      - SIGNUPS_DOMAINS_WHITELIST=studmail.w-hs.de,fachschaftinformatik.de
      - S3_BUCKET=production
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio
      - S3_USE_SSL=false
    depends_on:
      minio:
        condition: service_healthy
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - buckets:/data
    networks:
      - api
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5 

