name: CI

on:
  push:
    paths:
      - "database/migrations/**"
      - "database/queries/**"
      - "database/sqlite.yaml"
  pull_request:
    paths:
      - "database/migrations/**"
      - "database/queries/**"
      - "database/sqlite.yaml"

permissions:
  contents: read

jobs:
  generate:
    name: Generate Go dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod 
      - run: go generate ./...

